//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartW.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class GarmentWear
    {
        public int GarmentWearId { get; set; }
        public Nullable<int> GarmentId { get; set; }
        public Nullable<int> WearsId { get; set; }
    
        public virtual Garment Garment { get; set; }
        public virtual Wears Wears { get; set; }
    }
}
