//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartW.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Garment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Garment()
        {
            this.GarmentOutfit1 = new HashSet<GarmentOutfit>();
            this.GarmentWear1 = new HashSet<GarmentWear>();
        }
    
        public int GarmentId { get; set; }
        public Nullable<int> GarmentOutfit { get; set; }
        public string Season { get; set; }
        public string Weather { get; set; }
        public string Colour { get; set; }
        public string Features { get; set; }
        public Nullable<double> Price { get; set; }
        public string Fit { get; set; }
        public string Size { get; set; }
        public Nullable<int> GarmentWear { get; set; }
        public Nullable<int> Formality { get; set; }
        public Nullable<int> Mending { get; set; }
        public string Type { get; set; }
        public string ImagePath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GarmentOutfit> GarmentOutfit1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GarmentWear> GarmentWear1 { get; set; }
    }
}
